name: Publish to Raycast Store
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: timrogers/publish-raycast-extension@v1.0.1
        with:
          extension_name: pulsemcp
          github_access_token: ${{ secrets.RAYCAST_EXTENSIONS_TOKEN }}
          raycast_extensions_fork_full_name: ichoosetoaccept/extensions
          github_username: ichoosetoaccept
